version: '2.0'
services:
  rabbitmq:
    image: rabbitmq:latest
    hostname: test
  rabbitmq-management:
    image: rabbitmq:3-management
    ports:
      - 8080:15672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
